name: CI

on:
  push:
    tags:
      - 'v**'
    branches:
      - '**'
  pull_request:

  workflow_dispatch:

  # to execute once a day (more info see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule )
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ci-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build-check:
    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:26.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update system dependencies
        run: |
          apt update --yes

      - name: Install system dependencies
        run: |
          apt install --yes npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
